services:
  portainer:
    image: portainer/portainer-ce:lts
    networks:
      - portainer-network
      - edge-network
    volumes:
      - portainer-data:/data
    command: ["-H", "tcp://tasks.portainer-agent:9001", "--tlsskipverify"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == panel.domain.tld

  portainer-agent:
    image: portainer/agent:lts
    networks:
      - portainer-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global

networks:
  portainer-network:
    driver: overlay
  edge-network:
    driver: overlay
    external: true

volumes:
  portainer-data:
    driver: local
